
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Bill': typeof import("../components/Bill.vue")['default']
    'BillPreview': typeof import("../components/BillPreview.vue")['default']
    'BillSuccess': typeof import("../components/BillSuccess.vue")['default']
    'BillingChart': typeof import("../components/BillingChart.vue")['default']
    'BillingTable': typeof import("../components/BillingTable.vue")['default']
    'BottomNav': typeof import("../components/BottomNav.vue")['default']
    'ClusterConsumptionCompare': typeof import("../components/ClusterConsumptionCompare.vue")['default']
    'ClusterFacetedFilter': typeof import("../components/ClusterFacetedFilter.vue")['default']
    'ConsumptionStats': typeof import("../components/ConsumptionStats.vue")['default']
    'DataTable': typeof import("../components/DataTable.vue")['default']
    'DataTableFacetedFilter': typeof import("../components/DataTableFacetedFilter.vue")['default']
    'DatePicker': typeof import("../components/DatePicker.vue")['default']
    'DateRangePicker': typeof import("../components/DateRangePicker.vue")['default']
    'DeviceCard': typeof import("../components/DeviceCard.vue")['default']
    'DeviceClusterCard': typeof import("../components/DeviceClusterCard.vue")['default']
    'DeviceMonitoring': typeof import("../components/DeviceMonitoring.vue")['default']
    'DevicesSummary': typeof import("../components/DevicesSummary.vue")['default']
    'Drawer': typeof import("../components/Drawer.vue")['default']
    'DynamicBillPreview': typeof import("../components/DynamicBillPreview.vue")['default']
    'Header': typeof import("../components/Header.vue")['default']
    'Logo': typeof import("../components/Logo.vue")['default']
    'Modal': typeof import("../components/Modal.vue")['default']
    'MonthlyBillingStats': typeof import("../components/MonthlyBillingStats.vue")['default']
    'NewDevice': typeof import("../components/NewDevice.vue")['default']
    'PeriodFacetedFilter': typeof import("../components/PeriodFacetedFilter.vue")['default']
    'SideBar': typeof import("../components/SideBar.vue")['default']
    'SingleDeviceMonitoring': typeof import("../components/SingleDeviceMonitoring.vue")['default']
    'SmartCredit': typeof import("../components/SmartCredit.vue")['default']
    'Stat': typeof import("../components/Stat.vue")['default']
    'TotalPayableBillWidget': typeof import("../components/TotalPayableBillWidget.vue")['default']
    'UserFullAvatar': typeof import("../components/UserFullAvatar.vue")['default']
    'UserNav': typeof import("../components/UserNav.vue")['default']
    'UsersTable': typeof import("../components/UsersTable.vue")['default']
    'WaterConsumptionChart': typeof import("../components/WaterConsumptionChart.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'Avatar': typeof import("../components/ui/avatar/index")['Avatar']
    'AvatarImage': typeof import("../components/ui/avatar/index")['AvatarImage']
    'AvatarFallback': typeof import("../components/ui/avatar/index")['AvatarFallback']
    'Badge': typeof import("../components/ui/badge/index")['Badge']
    'Button': typeof import("../components/ui/button/index")['Button']
    'Calendar': typeof import("../components/ui/calendar/index")['Calendar']
    'Card': typeof import("../components/ui/card/index")['Card']
    'CardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'CardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'CardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'CardContent': typeof import("../components/ui/card/index")['CardContent']
    'CardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'ChartTooltip': typeof import("../components/ui/chart/index")['ChartTooltip']
    'ChartSingleTooltip': typeof import("../components/ui/chart/index")['ChartSingleTooltip']
    'ChartLegend': typeof import("../components/ui/chart/index")['ChartLegend']
    'ChartCrosshair': typeof import("../components/ui/chart/index")['ChartCrosshair']
    'AreaChart': typeof import("../components/ui/chart-area/index")['AreaChart']
    'Checkbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'Collapsible': typeof import("../components/ui/collapsible/index")['Collapsible']
    'CollapsibleTrigger': typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']
    'CollapsibleContent': typeof import("../components/ui/collapsible/index")['CollapsibleContent']
    'Dialog': typeof import("../components/ui/dialog/index")['Dialog']
    'DialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'DialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'DialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'DialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'DialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'DialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'DialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'DialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'DropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'DropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'DropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'DropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'DropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'DropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'DropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'DropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'DropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'DropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'DropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'DropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'DropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'DropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'DropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'Form': typeof import("../components/ui/form/index")['Form']
    'FormField': typeof import("../components/ui/form/index")['FormField']
    'FormItem': typeof import("../components/ui/form/index")['FormItem']
    'FormLabel': typeof import("../components/ui/form/index")['FormLabel']
    'FormControl': typeof import("../components/ui/form/index")['FormControl']
    'FormMessage': typeof import("../components/ui/form/index")['FormMessage']
    'FormDescription': typeof import("../components/ui/form/index")['FormDescription']
    'Input': typeof import("../components/ui/input/index")['Input']
    'Label': typeof import("../components/ui/label/index")['Label']
    'Pagination': typeof import("../components/ui/pagination/index")['Pagination']
    'PaginationList': typeof import("../components/ui/pagination/index")['PaginationList']
    'PaginationListItem': typeof import("../components/ui/pagination/index")['PaginationListItem']
    'PaginationEllipsis': typeof import("../components/ui/pagination/index")['PaginationEllipsis']
    'PaginationFirst': typeof import("../components/ui/pagination/index")['PaginationFirst']
    'PaginationLast': typeof import("../components/ui/pagination/index")['PaginationLast']
    'PaginationNext': typeof import("../components/ui/pagination/index")['PaginationNext']
    'PaginationPrev': typeof import("../components/ui/pagination/index")['PaginationPrev']
    'Popover': typeof import("../components/ui/popover/index")['Popover']
    'PopoverTrigger': typeof import("../components/ui/popover/index")['PopoverTrigger']
    'PopoverContent': typeof import("../components/ui/popover/index")['PopoverContent']
    'Select': typeof import("../components/ui/select/index")['Select']
    'SelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'SelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'SelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'SelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'SelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'SelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'SelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'SelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'SelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'SelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'Separator': typeof import("../components/ui/separator/index")['Separator']
    'Sheet': typeof import("../components/ui/sheet/index")['Sheet']
    'SheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'SheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'SheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'SheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'SheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'SheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'SheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'Skeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'Switch': typeof import("../components/ui/switch/index")['Switch']
    'Table': typeof import("../components/ui/table/index")['Table']
    'TableBody': typeof import("../components/ui/table/index")['TableBody']
    'TableCell': typeof import("../components/ui/table/index")['TableCell']
    'TableHead': typeof import("../components/ui/table/index")['TableHead']
    'TableHeader': typeof import("../components/ui/table/index")['TableHeader']
    'TableRow': typeof import("../components/ui/table/index")['TableRow']
    'TableCaption': typeof import("../components/ui/table/index")['TableCaption']
    'TableEmpty': typeof import("../components/ui/table/index")['TableEmpty']
    'Tooltip': typeof import("../components/ui/tooltip/index")['Tooltip']
    'TooltipContent': typeof import("../components/ui/tooltip/index")['TooltipContent']
    'TooltipTrigger': typeof import("../components/ui/tooltip/index")['TooltipTrigger']
    'TooltipProvider': typeof import("../components/ui/tooltip/index")['TooltipProvider']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBill': typeof import("../components/Bill.vue")['default']
    'LazyBillPreview': typeof import("../components/BillPreview.vue")['default']
    'LazyBillSuccess': typeof import("../components/BillSuccess.vue")['default']
    'LazyBillingChart': typeof import("../components/BillingChart.vue")['default']
    'LazyBillingTable': typeof import("../components/BillingTable.vue")['default']
    'LazyBottomNav': typeof import("../components/BottomNav.vue")['default']
    'LazyClusterConsumptionCompare': typeof import("../components/ClusterConsumptionCompare.vue")['default']
    'LazyClusterFacetedFilter': typeof import("../components/ClusterFacetedFilter.vue")['default']
    'LazyConsumptionStats': typeof import("../components/ConsumptionStats.vue")['default']
    'LazyDataTable': typeof import("../components/DataTable.vue")['default']
    'LazyDataTableFacetedFilter': typeof import("../components/DataTableFacetedFilter.vue")['default']
    'LazyDatePicker': typeof import("../components/DatePicker.vue")['default']
    'LazyDateRangePicker': typeof import("../components/DateRangePicker.vue")['default']
    'LazyDeviceCard': typeof import("../components/DeviceCard.vue")['default']
    'LazyDeviceClusterCard': typeof import("../components/DeviceClusterCard.vue")['default']
    'LazyDeviceMonitoring': typeof import("../components/DeviceMonitoring.vue")['default']
    'LazyDevicesSummary': typeof import("../components/DevicesSummary.vue")['default']
    'LazyDrawer': typeof import("../components/Drawer.vue")['default']
    'LazyDynamicBillPreview': typeof import("../components/DynamicBillPreview.vue")['default']
    'LazyHeader': typeof import("../components/Header.vue")['default']
    'LazyLogo': typeof import("../components/Logo.vue")['default']
    'LazyModal': typeof import("../components/Modal.vue")['default']
    'LazyMonthlyBillingStats': typeof import("../components/MonthlyBillingStats.vue")['default']
    'LazyNewDevice': typeof import("../components/NewDevice.vue")['default']
    'LazyPeriodFacetedFilter': typeof import("../components/PeriodFacetedFilter.vue")['default']
    'LazySideBar': typeof import("../components/SideBar.vue")['default']
    'LazySingleDeviceMonitoring': typeof import("../components/SingleDeviceMonitoring.vue")['default']
    'LazySmartCredit': typeof import("../components/SmartCredit.vue")['default']
    'LazyStat': typeof import("../components/Stat.vue")['default']
    'LazyTotalPayableBillWidget': typeof import("../components/TotalPayableBillWidget.vue")['default']
    'LazyUserFullAvatar': typeof import("../components/UserFullAvatar.vue")['default']
    'LazyUserNav': typeof import("../components/UserNav.vue")['default']
    'LazyUsersTable': typeof import("../components/UsersTable.vue")['default']
    'LazyWaterConsumptionChart': typeof import("../components/WaterConsumptionChart.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyAvatar': typeof import("../components/ui/avatar/index")['Avatar']
    'LazyAvatarImage': typeof import("../components/ui/avatar/index")['AvatarImage']
    'LazyAvatarFallback': typeof import("../components/ui/avatar/index")['AvatarFallback']
    'LazyBadge': typeof import("../components/ui/badge/index")['Badge']
    'LazyButton': typeof import("../components/ui/button/index")['Button']
    'LazyCalendar': typeof import("../components/ui/calendar/index")['Calendar']
    'LazyCard': typeof import("../components/ui/card/index")['Card']
    'LazyCardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'LazyCardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'LazyCardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'LazyCardContent': typeof import("../components/ui/card/index")['CardContent']
    'LazyCardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'LazyChartTooltip': typeof import("../components/ui/chart/index")['ChartTooltip']
    'LazyChartSingleTooltip': typeof import("../components/ui/chart/index")['ChartSingleTooltip']
    'LazyChartLegend': typeof import("../components/ui/chart/index")['ChartLegend']
    'LazyChartCrosshair': typeof import("../components/ui/chart/index")['ChartCrosshair']
    'LazyAreaChart': typeof import("../components/ui/chart-area/index")['AreaChart']
    'LazyCheckbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'LazyCollapsible': typeof import("../components/ui/collapsible/index")['Collapsible']
    'LazyCollapsibleTrigger': typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']
    'LazyCollapsibleContent': typeof import("../components/ui/collapsible/index")['CollapsibleContent']
    'LazyDialog': typeof import("../components/ui/dialog/index")['Dialog']
    'LazyDialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'LazyDialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'LazyDialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'LazyDialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'LazyDialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'LazyDialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'LazyDialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'LazyDialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'LazyDropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'LazyDropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'LazyDropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'LazyDropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'LazyDropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'LazyDropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'LazyDropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'LazyDropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'LazyDropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'LazyDropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'LazyDropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'LazyDropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'LazyDropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'LazyDropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'LazyDropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'LazyForm': typeof import("../components/ui/form/index")['Form']
    'LazyFormField': typeof import("../components/ui/form/index")['FormField']
    'LazyFormItem': typeof import("../components/ui/form/index")['FormItem']
    'LazyFormLabel': typeof import("../components/ui/form/index")['FormLabel']
    'LazyFormControl': typeof import("../components/ui/form/index")['FormControl']
    'LazyFormMessage': typeof import("../components/ui/form/index")['FormMessage']
    'LazyFormDescription': typeof import("../components/ui/form/index")['FormDescription']
    'LazyInput': typeof import("../components/ui/input/index")['Input']
    'LazyLabel': typeof import("../components/ui/label/index")['Label']
    'LazyPagination': typeof import("../components/ui/pagination/index")['Pagination']
    'LazyPaginationList': typeof import("../components/ui/pagination/index")['PaginationList']
    'LazyPaginationListItem': typeof import("../components/ui/pagination/index")['PaginationListItem']
    'LazyPaginationEllipsis': typeof import("../components/ui/pagination/index")['PaginationEllipsis']
    'LazyPaginationFirst': typeof import("../components/ui/pagination/index")['PaginationFirst']
    'LazyPaginationLast': typeof import("../components/ui/pagination/index")['PaginationLast']
    'LazyPaginationNext': typeof import("../components/ui/pagination/index")['PaginationNext']
    'LazyPaginationPrev': typeof import("../components/ui/pagination/index")['PaginationPrev']
    'LazyPopover': typeof import("../components/ui/popover/index")['Popover']
    'LazyPopoverTrigger': typeof import("../components/ui/popover/index")['PopoverTrigger']
    'LazyPopoverContent': typeof import("../components/ui/popover/index")['PopoverContent']
    'LazySelect': typeof import("../components/ui/select/index")['Select']
    'LazySelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'LazySelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'LazySelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'LazySelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'LazySelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'LazySelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'LazySelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'LazySelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'LazySelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'LazySelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'LazySeparator': typeof import("../components/ui/separator/index")['Separator']
    'LazySheet': typeof import("../components/ui/sheet/index")['Sheet']
    'LazySheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'LazySheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'LazySheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'LazySheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'LazySheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'LazySheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'LazySheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'LazySkeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'LazySwitch': typeof import("../components/ui/switch/index")['Switch']
    'LazyTable': typeof import("../components/ui/table/index")['Table']
    'LazyTableBody': typeof import("../components/ui/table/index")['TableBody']
    'LazyTableCell': typeof import("../components/ui/table/index")['TableCell']
    'LazyTableHead': typeof import("../components/ui/table/index")['TableHead']
    'LazyTableHeader': typeof import("../components/ui/table/index")['TableHeader']
    'LazyTableRow': typeof import("../components/ui/table/index")['TableRow']
    'LazyTableCaption': typeof import("../components/ui/table/index")['TableCaption']
    'LazyTableEmpty': typeof import("../components/ui/table/index")['TableEmpty']
    'LazyTooltip': typeof import("../components/ui/tooltip/index")['Tooltip']
    'LazyTooltipContent': typeof import("../components/ui/tooltip/index")['TooltipContent']
    'LazyTooltipTrigger': typeof import("../components/ui/tooltip/index")['TooltipTrigger']
    'LazyTooltipProvider': typeof import("../components/ui/tooltip/index")['TooltipProvider']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Bill: typeof import("../components/Bill.vue")['default']
export const BillPreview: typeof import("../components/BillPreview.vue")['default']
export const BillSuccess: typeof import("../components/BillSuccess.vue")['default']
export const BillingChart: typeof import("../components/BillingChart.vue")['default']
export const BillingTable: typeof import("../components/BillingTable.vue")['default']
export const BottomNav: typeof import("../components/BottomNav.vue")['default']
export const ClusterConsumptionCompare: typeof import("../components/ClusterConsumptionCompare.vue")['default']
export const ClusterFacetedFilter: typeof import("../components/ClusterFacetedFilter.vue")['default']
export const ConsumptionStats: typeof import("../components/ConsumptionStats.vue")['default']
export const DataTable: typeof import("../components/DataTable.vue")['default']
export const DataTableFacetedFilter: typeof import("../components/DataTableFacetedFilter.vue")['default']
export const DatePicker: typeof import("../components/DatePicker.vue")['default']
export const DateRangePicker: typeof import("../components/DateRangePicker.vue")['default']
export const DeviceCard: typeof import("../components/DeviceCard.vue")['default']
export const DeviceClusterCard: typeof import("../components/DeviceClusterCard.vue")['default']
export const DeviceMonitoring: typeof import("../components/DeviceMonitoring.vue")['default']
export const DevicesSummary: typeof import("../components/DevicesSummary.vue")['default']
export const Drawer: typeof import("../components/Drawer.vue")['default']
export const DynamicBillPreview: typeof import("../components/DynamicBillPreview.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const Logo: typeof import("../components/Logo.vue")['default']
export const Modal: typeof import("../components/Modal.vue")['default']
export const MonthlyBillingStats: typeof import("../components/MonthlyBillingStats.vue")['default']
export const NewDevice: typeof import("../components/NewDevice.vue")['default']
export const PeriodFacetedFilter: typeof import("../components/PeriodFacetedFilter.vue")['default']
export const SideBar: typeof import("../components/SideBar.vue")['default']
export const SingleDeviceMonitoring: typeof import("../components/SingleDeviceMonitoring.vue")['default']
export const SmartCredit: typeof import("../components/SmartCredit.vue")['default']
export const Stat: typeof import("../components/Stat.vue")['default']
export const TotalPayableBillWidget: typeof import("../components/TotalPayableBillWidget.vue")['default']
export const UserFullAvatar: typeof import("../components/UserFullAvatar.vue")['default']
export const UserNav: typeof import("../components/UserNav.vue")['default']
export const UsersTable: typeof import("../components/UsersTable.vue")['default']
export const WaterConsumptionChart: typeof import("../components/WaterConsumptionChart.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const Avatar: typeof import("../components/ui/avatar/index")['Avatar']
export const AvatarImage: typeof import("../components/ui/avatar/index")['AvatarImage']
export const AvatarFallback: typeof import("../components/ui/avatar/index")['AvatarFallback']
export const Badge: typeof import("../components/ui/badge/index")['Badge']
export const Button: typeof import("../components/ui/button/index")['Button']
export const Calendar: typeof import("../components/ui/calendar/index")['Calendar']
export const Card: typeof import("../components/ui/card/index")['Card']
export const CardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const CardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const CardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const CardContent: typeof import("../components/ui/card/index")['CardContent']
export const CardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const ChartTooltip: typeof import("../components/ui/chart/index")['ChartTooltip']
export const ChartSingleTooltip: typeof import("../components/ui/chart/index")['ChartSingleTooltip']
export const ChartLegend: typeof import("../components/ui/chart/index")['ChartLegend']
export const ChartCrosshair: typeof import("../components/ui/chart/index")['ChartCrosshair']
export const AreaChart: typeof import("../components/ui/chart-area/index")['AreaChart']
export const Checkbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const Collapsible: typeof import("../components/ui/collapsible/index")['Collapsible']
export const CollapsibleTrigger: typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']
export const CollapsibleContent: typeof import("../components/ui/collapsible/index")['CollapsibleContent']
export const Dialog: typeof import("../components/ui/dialog/index")['Dialog']
export const DialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const DialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const DialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const DialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const DialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const DialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const DialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const DialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const DropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const DropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const DropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const DropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const DropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const DropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const DropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const DropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const DropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const DropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const DropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const DropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const DropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const DropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const DropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const Form: typeof import("../components/ui/form/index")['Form']
export const FormField: typeof import("../components/ui/form/index")['FormField']
export const FormItem: typeof import("../components/ui/form/index")['FormItem']
export const FormLabel: typeof import("../components/ui/form/index")['FormLabel']
export const FormControl: typeof import("../components/ui/form/index")['FormControl']
export const FormMessage: typeof import("../components/ui/form/index")['FormMessage']
export const FormDescription: typeof import("../components/ui/form/index")['FormDescription']
export const Input: typeof import("../components/ui/input/index")['Input']
export const Label: typeof import("../components/ui/label/index")['Label']
export const Pagination: typeof import("../components/ui/pagination/index")['Pagination']
export const PaginationList: typeof import("../components/ui/pagination/index")['PaginationList']
export const PaginationListItem: typeof import("../components/ui/pagination/index")['PaginationListItem']
export const PaginationEllipsis: typeof import("../components/ui/pagination/index")['PaginationEllipsis']
export const PaginationFirst: typeof import("../components/ui/pagination/index")['PaginationFirst']
export const PaginationLast: typeof import("../components/ui/pagination/index")['PaginationLast']
export const PaginationNext: typeof import("../components/ui/pagination/index")['PaginationNext']
export const PaginationPrev: typeof import("../components/ui/pagination/index")['PaginationPrev']
export const Popover: typeof import("../components/ui/popover/index")['Popover']
export const PopoverTrigger: typeof import("../components/ui/popover/index")['PopoverTrigger']
export const PopoverContent: typeof import("../components/ui/popover/index")['PopoverContent']
export const Select: typeof import("../components/ui/select/index")['Select']
export const SelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const SelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const SelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const SelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const SelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const SelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const SelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const SelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const SelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const SelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const Separator: typeof import("../components/ui/separator/index")['Separator']
export const Sheet: typeof import("../components/ui/sheet/index")['Sheet']
export const SheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const SheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const SheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const SheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const SheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const SheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const SheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const Skeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const Switch: typeof import("../components/ui/switch/index")['Switch']
export const Table: typeof import("../components/ui/table/index")['Table']
export const TableBody: typeof import("../components/ui/table/index")['TableBody']
export const TableCell: typeof import("../components/ui/table/index")['TableCell']
export const TableHead: typeof import("../components/ui/table/index")['TableHead']
export const TableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const TableRow: typeof import("../components/ui/table/index")['TableRow']
export const TableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const TableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const Tooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const TooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const TooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const TooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBill: typeof import("../components/Bill.vue")['default']
export const LazyBillPreview: typeof import("../components/BillPreview.vue")['default']
export const LazyBillSuccess: typeof import("../components/BillSuccess.vue")['default']
export const LazyBillingChart: typeof import("../components/BillingChart.vue")['default']
export const LazyBillingTable: typeof import("../components/BillingTable.vue")['default']
export const LazyBottomNav: typeof import("../components/BottomNav.vue")['default']
export const LazyClusterConsumptionCompare: typeof import("../components/ClusterConsumptionCompare.vue")['default']
export const LazyClusterFacetedFilter: typeof import("../components/ClusterFacetedFilter.vue")['default']
export const LazyConsumptionStats: typeof import("../components/ConsumptionStats.vue")['default']
export const LazyDataTable: typeof import("../components/DataTable.vue")['default']
export const LazyDataTableFacetedFilter: typeof import("../components/DataTableFacetedFilter.vue")['default']
export const LazyDatePicker: typeof import("../components/DatePicker.vue")['default']
export const LazyDateRangePicker: typeof import("../components/DateRangePicker.vue")['default']
export const LazyDeviceCard: typeof import("../components/DeviceCard.vue")['default']
export const LazyDeviceClusterCard: typeof import("../components/DeviceClusterCard.vue")['default']
export const LazyDeviceMonitoring: typeof import("../components/DeviceMonitoring.vue")['default']
export const LazyDevicesSummary: typeof import("../components/DevicesSummary.vue")['default']
export const LazyDrawer: typeof import("../components/Drawer.vue")['default']
export const LazyDynamicBillPreview: typeof import("../components/DynamicBillPreview.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyLogo: typeof import("../components/Logo.vue")['default']
export const LazyModal: typeof import("../components/Modal.vue")['default']
export const LazyMonthlyBillingStats: typeof import("../components/MonthlyBillingStats.vue")['default']
export const LazyNewDevice: typeof import("../components/NewDevice.vue")['default']
export const LazyPeriodFacetedFilter: typeof import("../components/PeriodFacetedFilter.vue")['default']
export const LazySideBar: typeof import("../components/SideBar.vue")['default']
export const LazySingleDeviceMonitoring: typeof import("../components/SingleDeviceMonitoring.vue")['default']
export const LazySmartCredit: typeof import("../components/SmartCredit.vue")['default']
export const LazyStat: typeof import("../components/Stat.vue")['default']
export const LazyTotalPayableBillWidget: typeof import("../components/TotalPayableBillWidget.vue")['default']
export const LazyUserFullAvatar: typeof import("../components/UserFullAvatar.vue")['default']
export const LazyUserNav: typeof import("../components/UserNav.vue")['default']
export const LazyUsersTable: typeof import("../components/UsersTable.vue")['default']
export const LazyWaterConsumptionChart: typeof import("../components/WaterConsumptionChart.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyAvatar: typeof import("../components/ui/avatar/index")['Avatar']
export const LazyAvatarImage: typeof import("../components/ui/avatar/index")['AvatarImage']
export const LazyAvatarFallback: typeof import("../components/ui/avatar/index")['AvatarFallback']
export const LazyBadge: typeof import("../components/ui/badge/index")['Badge']
export const LazyButton: typeof import("../components/ui/button/index")['Button']
export const LazyCalendar: typeof import("../components/ui/calendar/index")['Calendar']
export const LazyCard: typeof import("../components/ui/card/index")['Card']
export const LazyCardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const LazyCardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const LazyCardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const LazyCardContent: typeof import("../components/ui/card/index")['CardContent']
export const LazyCardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const LazyChartTooltip: typeof import("../components/ui/chart/index")['ChartTooltip']
export const LazyChartSingleTooltip: typeof import("../components/ui/chart/index")['ChartSingleTooltip']
export const LazyChartLegend: typeof import("../components/ui/chart/index")['ChartLegend']
export const LazyChartCrosshair: typeof import("../components/ui/chart/index")['ChartCrosshair']
export const LazyAreaChart: typeof import("../components/ui/chart-area/index")['AreaChart']
export const LazyCheckbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const LazyCollapsible: typeof import("../components/ui/collapsible/index")['Collapsible']
export const LazyCollapsibleTrigger: typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']
export const LazyCollapsibleContent: typeof import("../components/ui/collapsible/index")['CollapsibleContent']
export const LazyDialog: typeof import("../components/ui/dialog/index")['Dialog']
export const LazyDialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const LazyDialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const LazyDialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const LazyDialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const LazyDialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const LazyDialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const LazyDialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const LazyDialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const LazyDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const LazyDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const LazyDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const LazyDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const LazyDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const LazyDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const LazyDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const LazyDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const LazyDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const LazyDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const LazyDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const LazyDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const LazyDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const LazyDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const LazyDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const LazyForm: typeof import("../components/ui/form/index")['Form']
export const LazyFormField: typeof import("../components/ui/form/index")['FormField']
export const LazyFormItem: typeof import("../components/ui/form/index")['FormItem']
export const LazyFormLabel: typeof import("../components/ui/form/index")['FormLabel']
export const LazyFormControl: typeof import("../components/ui/form/index")['FormControl']
export const LazyFormMessage: typeof import("../components/ui/form/index")['FormMessage']
export const LazyFormDescription: typeof import("../components/ui/form/index")['FormDescription']
export const LazyInput: typeof import("../components/ui/input/index")['Input']
export const LazyLabel: typeof import("../components/ui/label/index")['Label']
export const LazyPagination: typeof import("../components/ui/pagination/index")['Pagination']
export const LazyPaginationList: typeof import("../components/ui/pagination/index")['PaginationList']
export const LazyPaginationListItem: typeof import("../components/ui/pagination/index")['PaginationListItem']
export const LazyPaginationEllipsis: typeof import("../components/ui/pagination/index")['PaginationEllipsis']
export const LazyPaginationFirst: typeof import("../components/ui/pagination/index")['PaginationFirst']
export const LazyPaginationLast: typeof import("../components/ui/pagination/index")['PaginationLast']
export const LazyPaginationNext: typeof import("../components/ui/pagination/index")['PaginationNext']
export const LazyPaginationPrev: typeof import("../components/ui/pagination/index")['PaginationPrev']
export const LazyPopover: typeof import("../components/ui/popover/index")['Popover']
export const LazyPopoverTrigger: typeof import("../components/ui/popover/index")['PopoverTrigger']
export const LazyPopoverContent: typeof import("../components/ui/popover/index")['PopoverContent']
export const LazySelect: typeof import("../components/ui/select/index")['Select']
export const LazySelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const LazySelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const LazySelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const LazySelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const LazySelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const LazySelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const LazySelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const LazySelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const LazySelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const LazySelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const LazySeparator: typeof import("../components/ui/separator/index")['Separator']
export const LazySheet: typeof import("../components/ui/sheet/index")['Sheet']
export const LazySheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const LazySheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const LazySheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const LazySheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const LazySheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const LazySheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const LazySheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const LazySkeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const LazySwitch: typeof import("../components/ui/switch/index")['Switch']
export const LazyTable: typeof import("../components/ui/table/index")['Table']
export const LazyTableBody: typeof import("../components/ui/table/index")['TableBody']
export const LazyTableCell: typeof import("../components/ui/table/index")['TableCell']
export const LazyTableHead: typeof import("../components/ui/table/index")['TableHead']
export const LazyTableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const LazyTableRow: typeof import("../components/ui/table/index")['TableRow']
export const LazyTableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const LazyTableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const LazyTooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const LazyTooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const LazyTooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const LazyTooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
