// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/15/2024, 12:09:47 AM
const configMerger = require("/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/plugins/**/*.{js,ts,mjs}","/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/@/stores/**/*.{js,ts,mjs}","/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/@/components/ui/**/*.{js,ts,mjs}","/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/composables/**/*.{js,ts,mjs}","/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/utils/**/*.{js,ts,mjs}","/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/xybron/Documents/X/DEV/ENGAGE+/Engage+WebApp/app.config.{js,ts,mjs}"] }));

module.exports = config
